# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('diagID', models.AutoField(primary_key=True, serialize=False)),
                ('ICD9', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ICD10', models.CharField(max_length=6)),
                ('page', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
            ],
        ),
    ]
