# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagassist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('comorbID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('diagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagassist.Diagnoses')),
            ],
        ),
        migrations.CreateModel(
            name='Diagsymp',
            fields=[
                ('linkID', models.AutoField(primary_key=True, serialize=False)),
                ('symp1', models.IntegerField()),
                ('prevalent1', models.BooleanField()),
                ('symp2', models.IntegerField()),
                ('prevalent2', models.BooleanField()),
                ('symp3', models.IntegerField()),
                ('prevalent3', models.BooleanField()),
                ('symp4', models.IntegerField()),
                ('prevalent4', models.BooleanField()),
                ('symp5', models.IntegerField()),
                ('prevalent5', models.BooleanField()),
                ('symp6', models.IntegerField()),
                ('prevalent6', models.BooleanField()),
                ('diagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagassist.Diagnoses')),
            ],
        ),
        migrations.CreateModel(
            name='DiffDiag',
            fields=[
                ('diffID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='diagassist.Diagnoses')),
                ('differentialDiagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentialDiagnosis', to='diagassist.Diagnoses')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('sympID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
