# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagassist', '0003_auto_20170927_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnoses',
            new_name='Diagnostic',
        ),
    ]
