# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagassist', '0004_auto_20170927_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSymptom',
            fields=[
                ('clientSympID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preexisting',
            fields=[
                ('preexistingID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
        migrations.AddField(
            model_name='client',
            name='therapistID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='diagassist.Therapist'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='ICD10',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='preexisting',
            name='clientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagassist.Client'),
        ),
        migrations.AddField(
            model_name='preexisting',
            name='diagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagassist.Diagnostic'),
        ),
        migrations.AddField(
            model_name='clientsymptom',
            name='clientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagassist.Client'),
        ),
        migrations.AddField(
            model_name='clientsymptom',
            name='sympID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagassist.Symptom'),
        ),
    ]
