# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagassist', '0005_auto_20171003_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
