# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagassist', '0006_auto_20171005_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
