# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagassist', '0010_auto_20180131_1450'),
        ('diagassist', '0011_auto_20180131_1452'),
    ]

    operations = [
    ]
